### ISSUE TITLE
not work in iOS9

### ISSUE THREAD

**Issue by qiaoyan** [rs/SDURLCache#47]
seems it store the response but never ask the response in sdurlcache, in iOS 9. 
(NSCachedURLResponse *)cachedResponseForRequest:(NSURLRequest *)request never be called. Any similar case?

**Comment by rs** [comment]
This project is no longer necessary (since iOS 5 actually).

See https://github.com/rs/SDURLCache/blob/master/SDURLCache.m#L426-L427

**Comment by qiaoyan** [comment]
Thanks. It still works when enableForIOS5AndUp = YES. I found bug in other place.
